name: "[CI/CD]"

on: [push]

env:
  NODE_VERSION: 16.9.1
  RUBY_VERSION: 3.0.2

jobs:
  lints:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: bundle exec rubocop -P
        name: Lint Ruby files
      - run: bundle exec erblint app/**/*.erb
        name: Lint ERB files
  tests:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Setup test_app
        run: bundle exec rake test_app
      - name: Rspec unit tests
        run: bundle exec rspec --exclude-pattern "spec/system/**/*_spec.rb"
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
      - uses: actions/upload-artifact@v2-preview
        if: always()
        with:
          name: screenshots
          path: ./spec/decidim_dummy_app/tmp/screenshots
  system_tests:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Setup test_app
        run: bundle exec rake test_app
      - name: Rspec system tests
        run: bundle exec rspec --pattern "spec/system/**/*_spec.rb"
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
      - uses: actions/upload-artifact@v2-preview
        if: always()
        with:
          name: screenshots
          path: ./spec/decidim_dummy_app/tmp/screenshots

